# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.runs/synth_1/axi_bram_ctrl_0_synth.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-1364297-madsr2d2/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.cache/wt [current_project]
set_property parent.project_path /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/abc_tb_pkg.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/abc_axi_protocol_chkr.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/random.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/data_gen.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/abc_stim_gen.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/axi_bram_ctrl_0_exdes.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/axi_checker.vhd
  /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/axi_bram_ctrl_0_synth.vhd
}
read_ip -quiet /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/axi_bram_ctrl_0_exdes.xdc
set_property used_in_implementation false [get_files /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/imports/axi_bram_ctrl_0_exdes.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top axi_bram_ctrl_0_synth -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_bram_ctrl_0_synth.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file axi_bram_ctrl_0_synth_utilization_synth.rpt -pb axi_bram_ctrl_0_synth_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
