# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
# IP: The module: 'axi_bram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
# IP: The module: 'axi_bram_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/madsr2d2/DTU/dds/as2/axi_bram_ctrl_0_ex/axi_bram_ctrl_0_ex.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_bram_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
